apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbinterface-deployment
  labels:
    app: dbinterface
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dbinterface
  template:
    metadata:
      labels:
        app: dbinterface
    spec:
      containers:
        - name: dbinterface
          image: satyampsoni/dbinterface:1.0.0
          ports:
            - containerPort: 8080
